### ISSUE TITLE
Sandbox response breaks contract/causes error serializing

### ISSUE THREAD

**Issue by beefcheese** [ShipEngine/shipengine-dotnet#41]
Hello, it seems that delivery_days is defined as non-nullable in your API but my web service call (via this SDK) is erroring in the test environment.
Error converting value {null} to type 'System.Int32'. Path 'rate_response.rates[2].delivery_days', line 106, position 29.

   at ShipEngineSDK.ShipEngineClient.<SendHttpRequestAsync>d__5`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ShipEngineSDK.ShipEngine.<GetRatesWithShipmentDetails>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

Note that the addresses and accounts here are fake/test accounts
**Request**: {"shipment":{"ship_to":{"name":"Steve","address_line1":"123 Main St","city_locality":"South Lyon","state_province":"MI","postal_code":"48111","country_code":"US","address_residential_indicator":"no"},"ship_from":{"name":"Steve","phone":"248-224-4668","address_line1":"123 Main St","city_locality":"South Lyon","state_province":"MI","postal_code":"48111","country_code":"US","address_residential_indicator":"no"},"packages":[{"weight":{"value":7.5,"unit":"Pound"}}]},"rate_options":{"carrier_ids":["se-769864","se-769863"]}}

**Response**: HTTP/1.1 200 OK
{
  "rate_response": {
    "rates": [
      {
        "rate_id": "se-911782738",
        "rate_type": "shipment",
        "carrier_id": "se-769863",
        "shipping_amount": {
          "currency": "usd",
          "amount": 25.91
        },
        "insurance_amount": {
          "currency": "usd",
          "amount": 0.0
        },
        "confirmation_amount": {
          "currency": "usd",
          "amount": 0.0
        },
        "other_amount": {
          "currency": "usd",
          "amount": 0.00
        },
        "zone": null,
        "package_type": null,
        "delivery_days": 3,
        "guaranteed_service": true,
        "estimated_delivery_date": "2021-10-04T00:00:00Z",
        "carrier_delivery_days": null,
        "ship_date": "2021-10-01T00:00:00Z",
        "negotiated_rate": false,
        "service_type": "UPS 3 Day Select®",
        "service_code": "ups_3_day_select",
        "trackable": true,
        "carrier_code": "ups",
        "carrier_nickname": "ShipEngine Test Account - UPS",
        "carrier_friendly_name": "UPS",
        "validation_status": "valid",
        "warning_messages": [
          "Ship To Address Classification is changed from Commercial to Residential"
        ],
        "error_messages": []
      },
      {
        "rate_id": "se-911782739",
        "rate_type": "shipment",
        "carrier_id": "se-769863",
        "shipping_amount": {
          "currency": "usd",
          "amount": 87.94
        },
        "insurance_amount": {
          "currency": "usd",
          "amount": 0.0
        },
        "confirmation_amount": {
          "currency": "usd",
          "amount": 0.0
        },
        "other_amount": {
          "currency": "usd",
          "amount": 0.00
        },
        "zone": null,
        "package_type": null,
        "delivery_days": 1,
        "guaranteed_service": true,
        "estimated_delivery_date": "2021-10-02T00:00:00Z",
        "carrier_delivery_days": null,
        "ship_date": "2021-10-01T00:00:00Z",
        "negotiated_rate": false,
        "service_type": "UPS Next Day Air® Early",
        "service_code": "ups_next_day_air_early_am",
        "trackable": true,
        "carrier_code": "ups",
        "carrier_nickname": "ShipEngine Test Account - UPS",
        "carrier_friendly_name": "UPS",
        "validation_status": "valid",
        "warning_messages": [
          "Ship To Address Classification is changed from Commercial to Residential"
        ],
        "error_messages": []
      },
      {
        "rate_id": "se-911782740",
        "rate_type": "shipment",
        "carrier_id": "se-769863",
        "shipping_amount": {
          "currency": "usd",
          "amount": 17.51
        },
        "insurance_amount": {
          "currency": "usd",
          "amount": 0.0
        },
        "confirmation_amount": {
          "currency": "usd",
          "amount": 0.0
        },
        "other_amount": {
          "currency": "usd",
          "amount": 0.00
        },
        "zone": null,
        "package_type": null,
        **"delivery_days": null,**
        "guaranteed_service": false,
        "estimated_delivery_date": null,
        "carrier_delivery_days": null,
        "ship_date": "2021-10-01T00:00:00Z",
        "negotiated_rate": false,
        "service_type": "UPS® Ground",
        "service_code": "ups_ground",
        "trackable": true,
        "carrier_code": "ups",
        "carrier_nickname": "ShipEngine Test Account - UPS",
        "carrier_friendly_name": "UPS",
        "validation_status": "valid",
        "warning_messages": [
          "Ship To Address Classification is changed from Commercial to Residential"
        ],
        "error_messages": []
      },
      {
        "rate_id": "se-911782741",
        "rate_type": "shipment",
        "carrier_id": "se-769863",
        "shipping_amount": {
          "currency": "usd",
          "amount": 52.24
        },
        "insurance_amount": {
          "currency": "usd",
          "amount": 0.0
        },
        "confirmation_amount": {
          "currency": "usd",
          "amount": 0.0
        },
        "other_amount": {
          "currency": "usd",
          "amount": 0.00
        },
        "zone": null,
        "package_type": null,
        "delivery_days": 1,
        "guaranteed_service": true,
        "estimated_delivery_date": "2021-10-02T00:00:00Z",
        "carrier_delivery_days": null,
        "ship_date": "2021-10-01T00:00:00Z",
        "negotiated_rate": false,
        "service_type": "UPS Next Day Air Saver®",
        "service_code": "ups_next_day_air_saver",
        "trackable": true,
        "carrier_code": "ups",
        "carrier_nickname": "ShipEngine Test Account - UPS",
        "carrier_friendly_name": "UPS",
        "validation_status": "valid",
        "warning_messages": [
          "Ship To Address Classification is changed from Commercial to Residential"
        ],
        "error_messages": []
      },
      {
        "rate_id": "se-911782742",
        "rate_type": "shipment",
        "carrier_id": "se-769863",
        "shipping_amount": {
          "currency": "usd",
          "amount": 55.17
        },
        "insurance_amount": {
          "currency": "usd",
          "amount": 0.0
        },
        "confirmation_amount": {
          "currency": "usd",
          "amount": 0.0
        },
        "other_amount": {
          "currency": "usd",
          "amount": 0.00
        },
        "zone": null,
        "package_type": null,
        "delivery_days": 1,
        "guaranteed_service": true,
        "estimated_delivery_date": "2021-10-02T00:00:00Z",
        "carrier_delivery_days": null,
        "ship_date": "2021-10-01T00:00:00Z",
        "negotiated_rate": false,
        "service_type": "UPS Next Day Air®",
        "service_code": "ups_next_day_air",
        "trackable": true,
        "carrier_code": "ups",
        "carrier_nickname": "ShipEngine Test Account - UPS",
        "carrier_friendly_name": "UPS",
        "validation_status": "valid",
        "warning_messages": [
          "Ship To Address Classification is changed from Commercial to Residential"
        ],
        "error_messages": []
      },
      {
        "rate_id": "se-911782743",
        "rate_type": "shipment",
        "carrier_id": "se-769863",
        "shipping_amount": {
          "currency": "usd",
          "amount": 33.25
        },
        "insurance_amount": {
          "currency": "usd",
          "amount": 0.0
        },
        "confirmation_amount": {
          "currency": "usd",
          "amount": 0.0
        },
        "other_amount": {
          "currency": "usd",
          "amount": 0.00
        },
        "zone": null,
        "package_type": null,
        "delivery_days": 2,
        "guaranteed_service": true,
        "estimated_delivery_date": "2021-10-04T00:00:00Z",
        "carrier_delivery_days": null,
        "ship_date": "2021-10-01T00:00:00Z",
        "negotiated_rate": false,
        "service_type": "UPS 2nd Day Air®",
        "service_code": "ups_2nd_day_air",
        "trackable": true,
        "carrier_code": "ups",
        "carrier_nickname": "ShipEngine Test Account - UPS",
        "carrier_friendly_name": "UPS",
        "validation_status": "valid",
        "warning_messages": [
          "Ship To Address Classification is changed from Commercial to Residential"
        ],
        "error_messages": []
      }
    ],
    "invalid_rates": [],
    "rate_request_id": "se-103446263",
    "shipment_id": "se-168945144",
    "created_at": "2021-10-01T14:13:09.7170675Z",
    "status": "partial",
    "errors": [
      {
        "error_source": "shipengine",
        "error_type": "business_rules",
        "error_code": "unspecified",
        "message": "A shipping carrier error occurred: Could not find endpoint element with name 'RateServicePort.Sandbox' and contract 'FedExRate.v28.RatePortType' in the ServiceModel client configuration section. This might be because no configuration file was found for your application, or because no endpoint element matching this name could be found in the client element.",
        "carrier_id": "se-769864",
        "carrier_code": "fedex",
        "carrier_name": "FedEx"
      },
      {
        "error_source": "shipengine",
        "error_type": "business_rules",
        "error_code": "unspecified",
        "message": "A shipping carrier error occurred: Could not find endpoint element with name 'RateServicePort.Sandbox' and contract 'FedExRate.v28.RatePortType' in the ServiceModel client configuration section. This might be because no configuration file was found for your application, or because no endpoint element matching this name could be found in the client element.",
        "carrier_id": "se-769864",
        "carrier_code": "fedex",
        "carrier_name": "FedEx"
      }
    ]
  },
  "shipment_id": "se-168945144",
  "carrier_id": null,
  "service_code": null,
  "external_shipment_id": null,
  "ship_date": "2021-10-01T00:00:00Z",
  "created_at": "2021-10-01T14:13:09.05Z",
  "modified_at": "2021-10-01T14:13:09.04Z",
  "shipment_status": "pending",
  "ship_to": {
    "name": "Steve",
    "phone": null,
    "company_name": null,
    "address_line1": "123 Main St",
    "address_line2": null,
    "address_line3": null,
    "city_locality": "South Lyon",
    "state_province": "MI",
    "postal_code": "48111",
    "country_code": "US",
    "address_residential_indicator": "no"
  },
  "ship_from": {
    "name": "Steve",
    "phone": "248-224-4668",
    "company_name": null,
    "address_line1": "123 Main St",
    "address_line2": null,
    "address_line3": null,
    "city_locality": "South Lyon",
    "state_province": "MI",
    "postal_code": "48111",
    "country_code": "US",
    "address_residential_indicator": "unknown"
  },
  "warehouse_id": null,
  "return_to": {
    "name": "Steve",
    "phone": "248-224-4668",
    "company_name": null,
    "address_line1": "123 Main St",
    "address_line2": null,
    "address_line3": null,
    "city_locality": "South Lyon",
    "state_province": "MI",
    "postal_code": "48111",
    "country_code": "US",
    "address_residential_indicator": "unknown"
  },
  "confirmation": "none",
  "customs": {
    "contents": "merchandise",
    "customs_items": [],
    "non_delivery": "return_to_sender"
  },
  "external_order_id": null,
  "order_source_code": null,
  "advanced_options": {
    "bill_to_account": null,
    "bill_to_country_code": null,
    "bill_to_party": null,
    "bill_to_postal_code": null,
    "contains_alcohol": false,
    "delivered_duty_paid": false,
    "non_machinable": false,
    "saturday_delivery": false,
    "dry_ice": false,
    "dry_ice_weight": null,
    "fedex_freight": null,
    "freight_class": null,
    "custom_field1": null,
    "custom_field2": null,
    "custom_field3": null,
    "collect_on_delivery": null,
    "return_pickup_attempts": null
  },
  "insurance_provider": "none",
  "tags": [],
  "packages": [
    {
      "package_code": "package",
      "weight": {
        "value": 7.50,
        "unit": "pound"
      },
      "dimensions": {
        "unit": "inch",
        "length": 0.0,
        "width": 0.0,
        "height": 0.0
      },
      "insured_value": {
        "currency": "usd",
        "amount": 0.00
      },
      "label_messages": {
        "reference1": null,
        "reference2": null,
        "reference3": null
      },
      "external_package_id": null
    }
  ],
  "total_weight": {
    "value": 7.50,
    "unit": "pound"
  },
  "items": []
}

**Comment by Lierrmm** [comment]
+1, seems to be only affecting UPS.

**Comment by sushithegreat** [comment]
Fixed in 1.0.3
