### ISSUE TITLE
Missing Entries in ShipEngineSDK.ErrorCode

### ISSUE THREAD

**Issue by joeloudjinz** [ShipEngine/shipengine-dotnet#59]
Tried creating a shipping label on the server, it throw this exception:
``` JS
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Newtonsoft.Json.JsonSerializationException: Error converting value "invalid_date" to type 'ShipEngineSDK.ErrorCode'. Path 'errors[0].error_code', line 7, position 34.
       ---> System.ArgumentException: Requested value 'invalid_date' was not found.
         at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
         at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
         --- End of inner exception stack trace ---
```

going through the SDK code and trying again i realized that the real error is the following 
```JSON
{
  "request_id": "35cf27e6-872b-4fc2-8e8a-24c556b3650d",
  "errors": [
    {
      "error_source": "shipengine",
      "error_type": "validation",
      "error_code": "invalid_date",
      "message": "ship_date must equal today’s date or a future date",
      "field_name": "ship_date",
      "field_value": "2023-01-06T00:00:00Z"
    }
  ]
}
```

**So it looks like** `ShipEngineSDK.ErrorCode` **is missing some entries like** `invalid_date`

**Comment by AnneOReilly** [comment]
@joeloudjinz Apologies for the inconvenience!  We just added this error_code to the API yesterday, we've got an update to the SDK scheduled to use the new code (there are a few that we're adding).
