### ISSUE TITLE
getRatesWithShipmentDetails

### ISSUE THREAD

**Issue by wentao709** [ShipEngine/shipengine-dotnet#63]
Hi Devs,

I'm having trouble with this API: getRatesWithShipmentDetails

I'm calling it like this: 

const shipEngineResults = await shipengine.getRatesWithShipmentDetails(shippingInfo);

where shippingInfo = {
  rateOptions: {
    carrierIds: [ 'se-2884143', 'se-2884144', 'se-2884146' ],
    serviceCodes: []
  },
  shipment: {
    validateAddress: 'validate_only',
    confirmation: 'none',
    shipFrom: {
      name: 'Tom Hanks',
      phone: '7146129169',
      postalCode: '93306',
      companyName: 'Test Company',
      countryCode: 'US',
      addressLine1: '3218 Kaibab Avenue',
      addressLine2: '',
      cityLocality: 'Bakersfield',
      stateProvince: 'CA',
      addressResidentialIndicator: 'no'
    },
    shipTo: {
      name: 'Nxtlives Dev',
      phone: null,
      addressLine1: '800 W 6th St',
      addressLine2: null,
      cityLocality: 'Los Angeles',
      stateProvince: 'CA',
      countryCode: 'US',
      postalCode: '90017'
    },
    packages: [ [Object] ]
  }
}

Sometimes I get the error saying {
  err: ShipEngineError: The ShipEngine /v1/rates API timed out.
      at sendRequestWithRetry (/Users/wentaozhou/Documents/GitHub/nextsite_server/node_modules/shipengine/cjs/client/index.js:44:23)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.post (/Users/wentaozhou/Documents/GitHub/nextsite_server/node_modules/shipengine/cjs/client/index.js:14:12)
      at async Object.getRatesWithShipmentDetails (/Users/wentaozhou/Documents/GitHub/nextsite_server/node_modules/shipengine/cjs/get-rates-with-shipment-details/index.js:17:22)
      at async itemShipping (file:///Users/wentaozhou/Documents/GitHub/nextsite_server/utils/order.js:1109:31)
      at async file:///Users/wentaozhou/Documents/GitHub/nextsite_server/controllers/orderController.js:1579:26
      at async Promise.all (index 0)
      at async get_cart_shipping (file:///Users/wentaozhou/Documents/GitHub/nextsite_server/controllers/orderController.js:1569:23) {
    source: 'shipengine',
    type: 'system',
    code: 'timeout',
    requestID: undefined,
    url: URL {
      href: 'https://www.shipengine.com/docs/errors/codes/',
      origin: 'https://www.shipengine.com/',
      protocol: 'https:',
      username: '',
      password: '',
      host: '[www.shipengine.com](http://www.shipengine.com/)',
      hostname: '[www.shipengine.com](http://www.shipengine.com/)',
      port: '',
      pathname: '/docs/errors/codes/',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    }
  }
}

Please note that this error does not happen every time I call it using the same json input. I would say there's a 50% chance that the error occurs, and other times the call is successful. do you know why this occurs?

Thanks,
Wentao Zhou

**Comment by AnneOReilly** [comment]
Hey @wentao709 !  It looks like you're running the default timeout frame of 5 seconds.  In Sandbox, it's common for carriers not to meet this timeframe.  You can modify the timeout for the SDK as a configuration variable.  60 seconds will be the maximum.

https://github.com/ShipEngine/shipengine-dotnet/blob/9158d2467c15f23660fe687e7542586566af5a53/ShipEngine/Config.cs#L31

**Comment by wentao709** [comment]
hi, what is the right way to change the timeout?

**Comment by wentao709** [comment]
sorry I guess my question is how do I import ShipEngineConfig from the node module? 
I can import shipengine as 
import Shipengine from 'shipengine';

not sure how to import ShipEngineConfig to my node.js server

**Comment by brandonraphael** [comment]
Hey @AnneOReilly, I'm also working with @wentao709 on this, thanks for the assistance. We have configured shipEngine to have a 60 second timeout now in js:

```
const shipEngineConfig = {
  apiKey: config.shipengineKey,
  timeout: 60,
};
const shipengine = new ShipEngine(shipEngineConfig);
```

Below is the ship engine config (JSON stringified) at the time of call to `/v1/rates` using the the function:
`const shipEngineResults = await shipengine.getRatesWithShipmentDetails(shipment);`

```
Ship Engine config:

 ShipEngine {
   config: NormalizedConfig {
     apiKey: 'XXXXXXXXXXXXXXX',
     baseURL: URL {
       href: 'https://api.shipengine.com/',
       origin: 'https://api.shipengine.com',
       protocol: 'https:',
       username: '',
       password: '',
       host: 'api.shipengine.com',
       hostname: 'api.shipengine.com',
       port: '',
       pathname: '/',
       search: '',
       searchParams: URLSearchParams {},
       hash: ''
     },
     pageSize: 50,
     retries: 1,
     timeout: 60
   }
 }
```

We are still seeing the same timeout error with that config:
```
 itemShipping Error  ShipEngineError: The ShipEngine /v1/rates API timed out.
     at sendRequestWithRetry (/home/ec2-user/NxtLives/nextsite_server/node_modules/shipengine/cjs/client/index.js:44:23)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async Object.post (/home/ec2-user/NxtLives/nextsite_server/node_modules/shipengine/cjs/client/index.js:14:12)
     at async Object.getRatesWithShipmentDetails (/home/ec2-user/NxtLives/nextsite_server/node_modules/shipengine/cjs/get-rates-with-shipment-details/index.js:17:22)
     at async itemShipping (file:///home/ec2-user/NxtLives/nextsite_server/utils/order.js:1129:31)
     at async file:///home/ec2-user/NxtLives/nextsite_server/controllers/orderController.js:1646:26
     at async Promise.all (index 0)
     at async get_cart_shipping (file:///home/ec2-user/NxtLives/nextsite_server/controllers/orderController.js:1636:23) {
   source: 'shipengine',
   type: 'system',
   code: 'timeout',
   requestID: undefined,
   url: URL {
     href: 'https://www.shipengine.com/docs/errors/codes/',
     origin: 'https://www.shipengine.com',
     protocol: 'https:',
     username: '',
     password: '',
     host: 'www.shipengine.com',
     hostname: 'www.shipengine.com',
     port: '',
     pathname: '/docs/errors/codes/',
     search: '',
     searchParams: URLSearchParams {},
     hash: ''
   }
 }
```

Do you have any other ideas what could be causing this issue?

**Comment by wentao709** [comment]
Hey @brandonraphael I stopped seeing the error without any custom config. can you try that please?
